/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N0Gc5IYR9KU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { formatPrice } from "@/lib/utils";
import { format } from "date-fns";

interface PriceProps {
  price?: number;
  delta?: number;
  symbol?: string;
}

export function PriceCard({
  price = 69420,
  delta = -1337,
  symbol = "BTC",
}: PriceProps) {
  return (
    <Card className="w-fit gap-5 p-6 flex items-centerx xjustify-between bg-background rounded-lg shadow-lg">
      <div className="flex flex-col items-center justify-between">
        <div className="text-4xl font-bold">{`${formatPrice(price)}`}</div>
        <div className="mt-4 text-sm text-muted-foreground">
          <span className="font-bold">{`${symbol}`}</span>
          <span className="mx-2">•</span>
          <span>{format(new Date(), "MMM do hh:mmaa")}</span>
        </div>
      </div>
      {delta >= 0 ? (
        <div className="flex items-center gap-2 text-sm font-medium pl-2 bg-green-100 py-2 px-4 rounded-md">
          <TrendingUpIcon className="size-8 text-green-500" />
          <div className="flex flex-col">
            <span className="text-green-500">{`+${formatPrice(delta)}`}</span>
            <span className="text-green-700">{`+${(
              delta / price
            ).toLocaleString()}%`}</span>
          </div>
        </div>
      ) : (
        <div className="flex items-center gap-2 text-sm font-medium pl-2 bg-red-100 py-2 px-4 rounded-md">
          <TrendingDownIcon className="size-8 text-red-500" />
          <div className="flex flex-col">
            <span className="text-red-500">{`${formatPrice(delta)}`}</span>
            <span className="text-red-700">{`${(
              delta / price
            ).toLocaleString()}%`}</span>
          </div>
        </div>
      )}
    </Card>
  );
}

function TrendingUpIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  );
}

function TrendingDownIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 17 13.5 8.5 8.5 13.5 2 7" />
      <polyline points="16 17 22 17 22 11" />
    </svg>
  );
}
