/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AZvN1gR3rek
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { cn, formatPrice } from "@/lib/utils";
import { Medal } from "lucide-react";

interface Props {
  name?: string;
  symbol?: string;
  volume?: number;
  volumeChangePercentage24h?: number;
  rank?: number;
  marketCap?: number;
  totalSupply?: number;
  dominance?: number;
}

export function StatsCard({
  name = "Bitcoin",
  symbol = "BTC",
  volume = 69420,
  volumeChangePercentage24h = -13.37,
  rank = 1,
  marketCap = 1_000_000_000,
  totalSupply = 21_000_000,
  dominance = 50,
}: Props) {
  return (
    <Card className="w-fit max-w-md p-6 bg-background shadow-lg rounded-lg">
      <CardHeader className="flex flex-row items-center justify-between mb-4 p-0">
        <div className="flex items-center gap-4">
          <div>
            <CardTitle className="text-lg font-semibold">{name}</CardTitle>
            <CardDescription className="text-muted-foreground text-sm">
              ${symbol}
            </CardDescription>
          </div>
        </div>
        <div className="flex items-center gap-1 text-sm font-medium">
          <Medal className="w-4 h-4 text-muted-foreground" />
          <span>{rank}</span>
        </div>
      </CardHeader>
      <CardContent className="grid grid-cols-2 gap-x-10 gap-y-5 p-0">
        <div className="flex flex-col gap-1">
          <p className="text-muted-foreground text-sm">Volume</p>
          <p className="text-lg font-semibold">${volume.toLocaleString()}</p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-muted-foreground text-sm">Volume Change</p>
          <p
            className={cn(
              "text-lg font-semibold w-fit rounded-sm px-2",
              volumeChangePercentage24h >= 0
                ? "text-green-500 bg-green-100"
                : "text-red-500 bg-red-100"
            )}
          >
            {`${
              volumeChangePercentage24h > 0 ? "+" : ""
            }${volumeChangePercentage24h.toFixed(2)}`}
            %
          </p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-muted-foreground text-sm">Market Cap</p>
          <p className="text-lg font-semibold">{formatPrice(marketCap, 0)}</p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-muted-foreground text-sm">Total Supply</p>
          <p className="text-lg font-semibold">
            {totalSupply.toLocaleString()}
          </p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-muted-foreground text-sm">Dominance</p>
          <p className="text-lg font-semibold">{dominance}%</p>
        </div>
      </CardContent>
    </Card>
  );
}
