/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZigiP1cIbNo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export function StatsCardSkeleton() {
  return (
    <Card className="w-fit max-w-md p-6 bg-background shadow-lg rounded-lg">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-4">
          <div>
            <Skeleton className="h-5 w-24 rounded" />
            <Skeleton className="h-4 w-16 rounded mt-1" />
          </div>
        </div>
        <div className="flex items-center gap-2 text-sm font-medium">
          <Skeleton className="w-4 h-4 rounded" />
          <Skeleton className="w-4 h-4 rounded" />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-x-20 gap-y-5">
        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded" />
          <Skeleton className="h-6 w-20 rounded" />
        </div>
        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded" />
          <Skeleton className="h-6 w-20 rounded" />
        </div>
        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded" />
          <Skeleton className="h-6 w-20 rounded" />
        </div>
        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded" />
          <Skeleton className="h-6 w-20 rounded" />
        </div>
        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded" />
          <Skeleton className="h-6 w-20 rounded" />
        </div>
      </div>
    </Card>
  );
}
